{% set name = "sphinx-astropy" %}
{% set version = "1.1.1" %}
{% set git_url = "https://github.com/astropy/sphinx-astropy" %}
{% set sha256 = "82721cae68d2e58f7ed173c8ce20d36fd25e1d0cc5502e5ff6cc79a24a50229c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - sphinx >=1.4
    - astropy-sphinx-theme
    - numpydoc
    - sphinx-automodapi
    - sphinx-gallery
    - graphviz
  run:
    - python
    - sphinx >=1.4
    - astropy-sphinx-theme
    - numpydoc
    - sphinx-automodapi
    - sphinx-gallery
    - graphviz

test:
  imports:
    - sphinx
    - astropy_sphinx_theme
    - numpydoc
    - sphinx_astropy
    - sphinx_automodapi
    - sphinx_gallery

about:
  home: {{ git_url }}
  license: BSD
  summary: 'Sphinx extensions and configuration specific to the Astropy project'
  description: |
    This package serves two purposes: it provides a default Sphinx configuration
    and set of extensions specific to the Astropy project, and it acts as a
    meta-package by installing all required Sphinx extensions for the core
    Astropy package and other packages.
  doc_url: {{ git_url }}
  dev_url: {{ git_url }}

extra:
  recipe-maintainers:
    - astrofrog-conda-forge
    - drdavella
    - mwcraig
