travis:
  secure:
    BINSTAR_TOKEN: gIW7ZtPtWCB8hVYAtTPVvOvPhjP3Gzg11/OJPYXZpCg+jL55VjuxooP+f7mGcwcHJ6KVMz+yTUZ1lKX077SEaI98bZw6tiNy6p3Qb/+KMzJv5uYSxMUl0CJfhJg238PtwjayuM5S9DUJo5pOmZxk6oTej8+kjoQj2A7Tl7/bGk5PwgFjXG9x9rzvz0AQQbeogYkfken7J7PAbZg2t75XhTnbUb6dMHydw0pRtyrLCGBIF2NhcfjpC7P7Y5zJqmFPFaY/OUd+YjdEXIwWyQhRVjoD8E1A9NBTYgVwM/kj70s6kWNWQ8kHeaXt2oHWyPRwNFDdoHGi7JUwXUxNnmlgwB57yBXfQ4n3ULozLHRTf5iP3RdCqxNH2JBAy4egL1Xe4WyJR2jJPqNkCMklsXq5PD4vd7mje5kzeMXrkTmd0ka6QY6d5+bUufOXFLQSe++UxZLRFDyHLaRPYZ5kBb+dh8k32wZphIB4LWn07o6YAdkN4CpAWXvkCJ2GJqq1crRtkYyQHL5S53BARNdqX5NEd6AkkcUNycjwRntjq+ofGh36o20HtvN8TPa+iLJ64e/ZACUomawE+fA/ZzrOI1lEKPXZZxh324BKAewdMES92SMb0PFF5wfyev3QmeyRW0pfuh8OnlAkwGw+qasM8B0oF/M+nypXe00QrvfvUSpFdAM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
